#!/usr/bin/env perl
use alienfile;
 
probe [ qq{ $ENV{HOME}/.local/bin/poetry --version } ];
 
share {
  start_url 'https://install.python-poetry.org';
  plugin 'Download';
  plugin 'Extract::File';

  build [
    [ # https://github.com/python-poetry/install.python-poetry.org/issues/24
      # https://github.com/python-poetry/install.python-poetry.org/issues/52
      q{ sed -i -e 's/symlinks=False/symlinks=True/' %{alien.install.extract}/install-poetry.py } ],
    [ q{ POETRY_HOME=%{alien.install.prefix} python3 %{alien.install.extract}/install-poetry.py } ],
  ];
};
